# Conexão com o banco de dados
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#server
server.port=${PORT:8080}

#Configurações do Mercado Pago
mercadopago.access.token=APP_USR-4600097165099609-040216-56244ba43a76ea1e151e8040bb702866-3310907408